"""edited logs table

Revision ID: 3ff65eb41cf0
Revises: 7ac724cf60eb
Create Date: 2026-02-22 11:47:51.745954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ff65eb41cf0'
down_revision: Union[str, Sequence[str], None] = '7ac724cf60eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_logs_endpoint_key'), 'api_logs', type_='unique')
    op.drop_constraint(op.f('api_logs_request_body_key'), 'api_logs', type_='unique')
    op.drop_constraint(op.f('api_logs_response_body_key'), 'api_logs', type_='unique')
    op.drop_constraint(op.f('api_logs_status_code_key'), 'api_logs', type_='unique')
    op.drop_constraint(op.f('api_logs_time_taken_key'), 'api_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('api_logs_time_taken_key'), 'api_logs', ['time_taken'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('api_logs_status_code_key'), 'api_logs', ['status_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('api_logs_response_body_key'), 'api_logs', ['response_body'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('api_logs_request_body_key'), 'api_logs', ['request_body'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('api_logs_endpoint_key'), 'api_logs', ['endpoint'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
