name: Ping Backend Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call backend endpoint
        run: |
          curl -X GET "${{ secrets.SERVER_URL }}/"